// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: app/asset_svc.proto

package custody

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Keeper      *HolderRef             `protobuf:"bytes,8,opt,name=keeper"`
	xxx_hidden_Location    string                 `protobuf:"bytes,9,opt,name=location"`
	xxx_hidden_Listed      bool                   `protobuf:"varint,10,opt,name=listed"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AssetAddRequest) Reset() {
	*x = AssetAddRequest{}
	mi := &file_app_asset_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetAddRequest) ProtoMessage() {}

func (x *AssetAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *AssetAddRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *AssetAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *AssetAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *AssetAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *AssetAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *AssetAddRequest) GetKeeper() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Keeper
	}
	return nil
}

func (x *AssetAddRequest) GetLocation() string {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return ""
}

func (x *AssetAddRequest) GetListed() bool {
	if x != nil {
		return x.xxx_hidden_Listed
	}
	return false
}

func (x *AssetAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *AssetAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *AssetAddRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *AssetAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *AssetAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *AssetAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *AssetAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *AssetAddRequest) SetKeeper(v *HolderRef) {
	x.xxx_hidden_Keeper = v
}

func (x *AssetAddRequest) SetLocation(v string) {
	x.xxx_hidden_Location = v
}

func (x *AssetAddRequest) SetListed(v bool) {
	x.xxx_hidden_Listed = v
}

func (x *AssetAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *AssetAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AssetAddRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *AssetAddRequest) HasKeeper() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Keeper != nil
}

func (x *AssetAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *AssetAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AssetAddRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *AssetAddRequest) ClearKeeper() {
	x.xxx_hidden_Keeper = nil
}

func (x *AssetAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type AssetAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Tenant      *TenantRef
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	Keeper      *HolderRef
	Location    string
	Listed      bool
	DateCreated *timestamppb.Timestamp
}

func (b0 AssetAddRequest_builder) Build() *AssetAddRequest {
	m0 := &AssetAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Keeper = b.Keeper
	x.xxx_hidden_Location = b.Location
	x.xxx_hidden_Listed = b.Listed
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type AssetGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *AssetRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *AssetSelect           `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AssetGetRequest) Reset() {
	*x = AssetGetRequest{}
	mi := &file_app_asset_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetGetRequest) ProtoMessage() {}

func (x *AssetGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetGetRequest) GetRef() *AssetRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AssetGetRequest) GetSelect() *AssetSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *AssetGetRequest) SetRef(v *AssetRef) {
	x.xxx_hidden_Ref = v
}

func (x *AssetGetRequest) SetSelect(v *AssetSelect) {
	x.xxx_hidden_Select = v
}

func (x *AssetGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AssetGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *AssetGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AssetGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type AssetGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *AssetRef
	Select *AssetSelect
}

func (b0 AssetGetRequest_builder) Build() *AssetGetRequest {
	m0 := &AssetGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type AssetRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isAssetRef_Key         `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetRef) Reset() {
	*x = AssetRef{}
	mi := &file_app_asset_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRef) ProtoMessage() {}

func (x *AssetRef) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*assetRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *AssetRef) GetSlug() *AssetRefBySlug {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*assetRef_Slug); ok {
			return x.Slug
		}
	}
	return nil
}

func (x *AssetRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &assetRef_Id{v}
}

func (x *AssetRef) SetSlug(v *AssetRefBySlug) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &assetRef_Slug{v}
}

func (x *AssetRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *AssetRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*assetRef_Id)
	return ok
}

func (x *AssetRef) HasSlug() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*assetRef_Slug)
	return ok
}

func (x *AssetRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *AssetRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*assetRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *AssetRef) ClearSlug() {
	if _, ok := x.xxx_hidden_Key.(*assetRef_Slug); ok {
		x.xxx_hidden_Key = nil
	}
}

const AssetRef_Key_not_set_case case_AssetRef_Key = 0
const AssetRef_Id_case case_AssetRef_Key = 1
const AssetRef_Slug_case case_AssetRef_Key = 4

func (x *AssetRef) WhichKey() case_AssetRef_Key {
	if x == nil {
		return AssetRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *assetRef_Id:
		return AssetRef_Id_case
	case *assetRef_Slug:
		return AssetRef_Slug_case
	default:
		return AssetRef_Key_not_set_case
	}
}

type AssetRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id   []byte
	Slug *AssetRefBySlug
	// -- end of xxx_hidden_Key
}

func (b0 AssetRef_builder) Build() *AssetRef {
	m0 := &AssetRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &assetRef_Id{b.Id}
	}
	if b.Slug != nil {
		x.xxx_hidden_Key = &assetRef_Slug{b.Slug}
	}
	return m0
}

type case_AssetRef_Key protoreflect.FieldNumber

func (x case_AssetRef_Key) String() string {
	md := file_app_asset_svc_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAssetRef_Key interface {
	isAssetRef_Key()
}

type assetRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type assetRef_Slug struct {
	Slug *AssetRefBySlug `protobuf:"bytes,4,opt,name=slug,oneof"`
}

func (*assetRef_Id) isAssetRef_Key() {}

func (*assetRef_Slug) isAssetRef_Key() {}

type AssetRefBySlug struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AssetRefBySlug) Reset() {
	*x = AssetRefBySlug{}
	mi := &file_app_asset_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetRefBySlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRefBySlug) ProtoMessage() {}

func (x *AssetRefBySlug) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetRefBySlug) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *AssetRefBySlug) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *AssetRefBySlug) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AssetRefBySlug) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *AssetRefBySlug) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AssetRefBySlug) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *AssetRefBySlug) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *AssetRefBySlug) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type AssetRefBySlug_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias  *string
	Tenant *TenantRef
}

func (b0 AssetRefBySlug_builder) Build() *AssetRefBySlug {
	m0 := &AssetRefBySlug{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_Tenant = b.Tenant
	return m0
}

type AssetSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Tenant      *TenantSelect          `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_Keeper      *HolderSelect          `protobuf:"bytes,8,opt,name=keeper"`
	xxx_hidden_Location    bool                   `protobuf:"varint,9,opt,name=location"`
	xxx_hidden_Listed      bool                   `protobuf:"varint,10,opt,name=listed"`
	xxx_hidden_DateUpdated bool                   `protobuf:"varint,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AssetSelect) Reset() {
	*x = AssetSelect{}
	mi := &file_app_asset_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSelect) ProtoMessage() {}

func (x *AssetSelect) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *AssetSelect) GetTenant() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *AssetSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *AssetSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *AssetSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *AssetSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *AssetSelect) GetKeeper() *HolderSelect {
	if x != nil {
		return x.xxx_hidden_Keeper
	}
	return nil
}

func (x *AssetSelect) GetLocation() bool {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return false
}

func (x *AssetSelect) GetListed() bool {
	if x != nil {
		return x.xxx_hidden_Listed
	}
	return false
}

func (x *AssetSelect) GetDateUpdated() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return false
}

func (x *AssetSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *AssetSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *AssetSelect) SetTenant(v *TenantSelect) {
	x.xxx_hidden_Tenant = v
}

func (x *AssetSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *AssetSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *AssetSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *AssetSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *AssetSelect) SetKeeper(v *HolderSelect) {
	x.xxx_hidden_Keeper = v
}

func (x *AssetSelect) SetLocation(v bool) {
	x.xxx_hidden_Location = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *AssetSelect) SetListed(v bool) {
	x.xxx_hidden_Listed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *AssetSelect) SetDateUpdated(v bool) {
	x.xxx_hidden_DateUpdated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *AssetSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *AssetSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AssetSelect) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *AssetSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AssetSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AssetSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AssetSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AssetSelect) HasKeeper() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Keeper != nil
}

func (x *AssetSelect) HasLocation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AssetSelect) HasListed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *AssetSelect) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *AssetSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *AssetSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *AssetSelect) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *AssetSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = false
}

func (x *AssetSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = false
}

func (x *AssetSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Desc = false
}

func (x *AssetSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Labels = false
}

func (x *AssetSelect) ClearKeeper() {
	x.xxx_hidden_Keeper = nil
}

func (x *AssetSelect) ClearLocation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Location = false
}

func (x *AssetSelect) ClearListed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Listed = false
}

func (x *AssetSelect) ClearDateUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DateUpdated = false
}

func (x *AssetSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_DateCreated = false
}

type AssetSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Tenant      *TenantSelect
	Alias       *bool
	Name        *bool
	Desc        *bool
	Labels      *bool
	Keeper      *HolderSelect
	Location    *bool
	Listed      *bool
	DateUpdated *bool
	DateCreated *bool
}

func (b0 AssetSelect_builder) Build() *AssetSelect {
	m0 := &AssetSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_Labels = *b.Labels
	}
	x.xxx_hidden_Keeper = b.Keeper
	if b.Location != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_Location = *b.Location
	}
	if b.Listed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_Listed = *b.Listed
	}
	if b.DateUpdated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_DateUpdated = *b.DateUpdated
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type AssetPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *AssetRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Tenant           *TenantRef             `protobuf:"bytes,4,opt,name=tenant"`
	xxx_hidden_Alias            *string                `protobuf:"bytes,8,opt,name=alias"`
	xxx_hidden_Name             *string                `protobuf:"bytes,10,opt,name=name"`
	xxx_hidden_Desc             *string                `protobuf:"bytes,12,opt,name=desc"`
	xxx_hidden_Labels           map[string]string      `protobuf:"bytes,14,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Keeper           *HolderRef             `protobuf:"bytes,16,opt,name=keeper"`
	xxx_hidden_KeeperNull       bool                   `protobuf:"varint,17,opt,name=keeper_null,json=keeperNull"`
	xxx_hidden_Location         *string                `protobuf:"bytes,18,opt,name=location"`
	xxx_hidden_Listed           bool                   `protobuf:"varint,20,opt,name=listed"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateUpdatedForce bool                   `protobuf:"varint,27,opt,name=date_updated_force,json=dateUpdatedForce"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AssetPatchRequest) Reset() {
	*x = AssetPatchRequest{}
	mi := &file_app_asset_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPatchRequest) ProtoMessage() {}

func (x *AssetPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetPatchRequest) GetRef() *AssetRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AssetPatchRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *AssetPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *AssetPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *AssetPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *AssetPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *AssetPatchRequest) GetKeeper() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Keeper
	}
	return nil
}

func (x *AssetPatchRequest) GetKeeperNull() bool {
	if x != nil {
		return x.xxx_hidden_KeeperNull
	}
	return false
}

func (x *AssetPatchRequest) GetLocation() string {
	if x != nil {
		if x.xxx_hidden_Location != nil {
			return *x.xxx_hidden_Location
		}
		return ""
	}
	return ""
}

func (x *AssetPatchRequest) GetListed() bool {
	if x != nil {
		return x.xxx_hidden_Listed
	}
	return false
}

func (x *AssetPatchRequest) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *AssetPatchRequest) GetDateUpdatedForce() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdatedForce
	}
	return false
}

func (x *AssetPatchRequest) SetRef(v *AssetRef) {
	x.xxx_hidden_Ref = v
}

func (x *AssetPatchRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *AssetPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *AssetPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *AssetPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *AssetPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *AssetPatchRequest) SetKeeper(v *HolderRef) {
	x.xxx_hidden_Keeper = v
}

func (x *AssetPatchRequest) SetKeeperNull(v bool) {
	x.xxx_hidden_KeeperNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *AssetPatchRequest) SetLocation(v string) {
	x.xxx_hidden_Location = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *AssetPatchRequest) SetListed(v bool) {
	x.xxx_hidden_Listed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *AssetPatchRequest) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *AssetPatchRequest) SetDateUpdatedForce(v bool) {
	x.xxx_hidden_DateUpdatedForce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *AssetPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AssetPatchRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *AssetPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AssetPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AssetPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AssetPatchRequest) HasKeeper() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Keeper != nil
}

func (x *AssetPatchRequest) HasKeeperNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AssetPatchRequest) HasLocation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *AssetPatchRequest) HasListed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *AssetPatchRequest) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *AssetPatchRequest) HasDateUpdatedForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *AssetPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AssetPatchRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *AssetPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = nil
}

func (x *AssetPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = nil
}

func (x *AssetPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Desc = nil
}

func (x *AssetPatchRequest) ClearKeeper() {
	x.xxx_hidden_Keeper = nil
}

func (x *AssetPatchRequest) ClearKeeperNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_KeeperNull = false
}

func (x *AssetPatchRequest) ClearLocation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Location = nil
}

func (x *AssetPatchRequest) ClearListed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Listed = false
}

func (x *AssetPatchRequest) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *AssetPatchRequest) ClearDateUpdatedForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_DateUpdatedForce = false
}

type AssetPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *AssetRef
	Tenant *TenantRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
	Keeper *HolderRef
	// Clear keeper instead of writing it.
	// It takes a field of its own because an unset value already means
	// "leave it alone", so no value could have meant NULL. It wins
	// outright: setting both this and keeper clears.
	KeeperNull *bool
	Location   *string
	Listed     *bool
	// The version this update requires the stored date_updated to be.
	// It is a precondition, not a write: the update applies only if the row
	// still holds this value, and the server stamps the new version itself.
	// Setting it together with date_updated_force is an error --
	// the version is the token every client's compare-and-swap is measured
	// against, so it is not the caller's to choose.
	DateUpdated *timestamppb.Timestamp
	// Update whatever the stored date_updated is, with no precondition.
	// The server still stamps a new version, so other clients' tokens are
	// invalidated as usual; this declines the check for THIS update only.
	// One of date_updated or this must be set. An omitted version is
	// refused rather than assumed, because an unset field cannot be told
	// apart from a caller who never considered locking at all.
	DateUpdatedForce *bool
}

func (b0 AssetPatchRequest_builder) Build() *AssetPatchRequest {
	m0 := &AssetPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Keeper = b.Keeper
	if b.KeeperNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_KeeperNull = *b.KeeperNull
	}
	if b.Location != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_Location = b.Location
	}
	if b.Listed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_Listed = *b.Listed
	}
	x.xxx_hidden_DateUpdated = b.DateUpdated
	if b.DateUpdatedForce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_DateUpdatedForce = *b.DateUpdatedForce
	}
	return m0
}

type AssetApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *AssetRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetApplyRequest) Reset() {
	*x = AssetApplyRequest{}
	mi := &file_app_asset_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetApplyRequest) ProtoMessage() {}

func (x *AssetApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetApplyRequest) GetRef() *AssetRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AssetApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *AssetApplyRequest) SetRef(v *AssetRef) {
	x.xxx_hidden_Ref = v
}

func (x *AssetApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *AssetApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AssetApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *AssetApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AssetApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type AssetApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *AssetRef
	Patch *patchpb.Patch
}

func (b0 AssetApplyRequest_builder) Build() *AssetApplyRequest {
	m0 := &AssetApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type AssetListRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*AssetFilter        `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size    int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After   string                 `protobuf:"bytes,3,opt,name=after"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssetListRequest) Reset() {
	*x = AssetListRequest{}
	mi := &file_app_asset_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetListRequest) ProtoMessage() {}

func (x *AssetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetListRequest) GetFilters() []*AssetFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *AssetListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *AssetListRequest) GetAfter() string {
	if x != nil {
		return x.xxx_hidden_After
	}
	return ""
}

func (x *AssetListRequest) SetFilters(v []*AssetFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *AssetListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
}

func (x *AssetListRequest) SetAfter(v string) {
	x.xxx_hidden_After = v
}

type AssetListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is: each filter is a predicate in the same query,
	// so this is what says how much of the database one request may read.
	Filters []*AssetFilter
	// How many to answer with. Nothing said is what the schema declared, and more
	// than the cap is the cap -- a caller asking for more than there is meant no
	// harm, so it is not an error and it is not the whole table either.
	Size int32
	// Where to carry on from: the "next" of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a row added
	// ahead of the page does not shift it and a caller reading through never sees
	// one twice or misses one.
	After string
}

func (b0 AssetListRequest_builder) Build() *AssetListRequest {
	m0 := &AssetListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_After = b.After
	return m0
}

type AssetListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Asset              `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next  string                 `protobuf:"bytes,2,opt,name=next"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetListResponse) Reset() {
	*x = AssetListResponse{}
	mi := &file_app_asset_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetListResponse) ProtoMessage() {}

func (x *AssetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetListResponse) GetItems() []*Asset {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *AssetListResponse) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *AssetListResponse) SetItems(v []*Asset) {
	x.xxx_hidden_Items = &v
}

func (x *AssetListResponse) SetNext(v string) {
	x.xxx_hidden_Next = v
}

type AssetListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Asset
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing the server can only know by having
	// looked.
	Next string
}

func (b0 AssetListResponse_builder) Build() *AssetListResponse {
	m0 := &AssetListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Next = b.Next
	return m0
}

type AssetFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *AssetRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Listed      bool                   `protobuf:"varint,2,opt,name=listed"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AssetFilter) Reset() {
	*x = AssetFilter{}
	mi := &file_app_asset_svc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetFilter) ProtoMessage() {}

func (x *AssetFilter) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetFilter) GetRef() *AssetRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AssetFilter) GetListed() bool {
	if x != nil {
		return x.xxx_hidden_Listed
	}
	return false
}

func (x *AssetFilter) SetRef(v *AssetRef) {
	x.xxx_hidden_Ref = v
}

func (x *AssetFilter) SetListed(v bool) {
	x.xxx_hidden_Listed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AssetFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AssetFilter) HasListed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AssetFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AssetFilter) ClearListed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Listed = false
}

type AssetFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *AssetRef
	Listed *bool
}

func (b0 AssetFilter_builder) Build() *AssetFilter {
	m0 := &AssetFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Listed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Listed = *b.Listed
	}
	return m0
}

type AssetWatchRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters      *[]*AssetFilter        `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_SkipSnapshot bool                   `protobuf:"varint,2,opt,name=skip_snapshot,json=skipSnapshot"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AssetWatchRequest) Reset() {
	*x = AssetWatchRequest{}
	mi := &file_app_asset_svc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetWatchRequest) ProtoMessage() {}

func (x *AssetWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetWatchRequest) GetFilters() []*AssetFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *AssetWatchRequest) GetSkipSnapshot() bool {
	if x != nil {
		return x.xxx_hidden_SkipSnapshot
	}
	return false
}

func (x *AssetWatchRequest) SetFilters(v []*AssetFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *AssetWatchRequest) SetSkipSnapshot(v bool) {
	x.xxx_hidden_SkipSnapshot = v
}

type AssetWatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which rows to watch, in the same words List takes them: what is watched is
	// what that list would answer with, now and afterwards.
	//
	// Required, and bounded the way a List is -- for a heavier reason. A list
	// runs its filters once; a watch runs them again for every write that touches
	// the entity, for as long as the stream is open. A watch with no filters is
	// the whole table, forever, which is the one shape that has no cap at all.
	Filters []*AssetFilter
	// Skip what is there now and send only what changes from here.
	//
	// Off by default, and the default is the safe one: a client that does not
	// know the current state and did not ask for it holds something wrong until
	// the next write happens to correct it.
	SkipSnapshot bool
}

func (b0 AssetWatchRequest_builder) Build() *AssetWatchRequest {
	m0 := &AssetWatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_SkipSnapshot = b.SkipSnapshot
	return m0
}

type AssetWatchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*AssetWatchItem     `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetWatchResponse) Reset() {
	*x = AssetWatchResponse{}
	mi := &file_app_asset_svc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetWatchResponse) ProtoMessage() {}

func (x *AssetWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetWatchResponse) GetItems() []*AssetWatchItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *AssetWatchResponse) SetItems(v []*AssetWatchItem) {
	x.xxx_hidden_Items = &v
}

type AssetWatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// What changed, or -- in the first message -- everything that matches.
	Items []*AssetWatchItem
}

func (b0 AssetWatchResponse_builder) Build() *AssetWatchResponse {
	m0 := &AssetWatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type AssetWatchItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       *Asset                 `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Action      string                 `protobuf:"bytes,3,opt,name=action"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AssetWatchItem) Reset() {
	*x = AssetWatchItem{}
	mi := &file_app_asset_svc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetWatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetWatchItem) ProtoMessage() {}

func (x *AssetWatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetWatchItem) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *AssetWatchItem) GetValue() *Asset {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *AssetWatchItem) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *AssetWatchItem) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AssetWatchItem) SetValue(v *Asset) {
	x.xxx_hidden_Value = v
}

func (x *AssetWatchItem) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *AssetWatchItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AssetWatchItem) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *AssetWatchItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AssetWatchItem) ClearValue() {
	x.xxx_hidden_Value = nil
}

type AssetWatchItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which row. Always said, since one that is gone still has to be named.
	Id []byte
	// The row as it is now, and **absent when it is no longer one this caller may
	// see**: erased, or moved out of the filters this stream named.
	//
	// Absence is the whole of how a removal is said. There is no flag for it, and
	// there is deliberately no way to tell those two apart -- a stream that
	// distinguished "erased" from "no longer yours" would be telling a caller
	// about rows that stopped being theirs, which is the thing the wall is for.
	//
	// It is only ever said about a row this stream has already carried. One that
	// never matched is not news.
	Value *Asset
	// The RPC that changed it, by the name gRPC knows it by. It is what the
	// caller of *that* RPC asked for and not the write it became, so an RPC
	// written by hand is here under its own name.
	//
	// Empty in the first message, which is not something anybody asked for -- it
	// is what is already there.
	Action string
}

func (b0 AssetWatchItem_builder) Build() *AssetWatchItem {
	m0 := &AssetWatchItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Action = b.Action
	return m0
}

type AssetTransferRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *AssetRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_To          *TenantRef             `protobuf:"bytes,2,opt,name=to"`
	xxx_hidden_Reason      *string                `protobuf:"bytes,3,opt,name=reason"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AssetTransferRequest) Reset() {
	*x = AssetTransferRequest{}
	mi := &file_app_asset_svc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTransferRequest) ProtoMessage() {}

func (x *AssetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_svc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AssetTransferRequest) GetRef() *AssetRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AssetTransferRequest) GetTo() *TenantRef {
	if x != nil {
		return x.xxx_hidden_To
	}
	return nil
}

func (x *AssetTransferRequest) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *AssetTransferRequest) SetRef(v *AssetRef) {
	x.xxx_hidden_Ref = v
}

func (x *AssetTransferRequest) SetTo(v *TenantRef) {
	x.xxx_hidden_To = v
}

func (x *AssetTransferRequest) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AssetTransferRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AssetTransferRequest) HasTo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_To != nil
}

func (x *AssetTransferRequest) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AssetTransferRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AssetTransferRequest) ClearTo() {
	x.xxx_hidden_To = nil
}

func (x *AssetTransferRequest) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Reason = nil
}

type AssetTransferRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The asset, named the way anything else names one. It is read through the
	// wall, so a caller who cannot see it is told NotFound rather than refused --
	// that it exists is itself something not to say.
	Ref *AssetRef
	// Where it goes.
	//
	// Whether the caller may name this tenant is the whole of the rule, and it is
	// not a predicate: the row has not moved yet, so there is nothing to narrow.
	// It is the same shape as payday's own "a holder is added to a tenant you can
	// see", which is a layer rather than a wall.
	To *TenantRef
	// Why, for the trail. Required, because a transfer with no reason is one
	// nobody can explain a year later.
	Reason *string
}

func (b0 AssetTransferRequest_builder) Build() *AssetTransferRequest {
	m0 := &AssetTransferRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_To = b.To
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Reason = b.Reason
	}
	return m0
}

var File_app_asset_svc_proto protoreflect.FileDescriptor

const file_app_asset_svc_proto_rawDesc = "" +
	"\n" +
	"\x13app/asset_svc.proto\x12\x03app\x1a\x0fapp/asset.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\x1a\x17payday/holder_svc.proto\x1a\x17payday/tenant_svc.proto\"\xc0\x03\n" +
	"\x0fAssetAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.payday.TenantRefR\x06tenant\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x128\n" +
	"\x06labels\x18\a \x03(\v2 .app.AssetAddRequest.LabelsEntryR\x06labels\x12)\n" +
	"\x06keeper\x18\b \x01(\v2\x11.payday.HolderRefR\x06keeper\x12!\n" +
	"\blocation\x18\t \x01(\tB\x05\xaa\x01\x02\b\x02R\blocation\x12\x1d\n" +
	"\x06listed\x18\n" +
	" \x01(\bB\x05\xaa\x01\x02\b\x02R\x06listed\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x0fAssetGetRequest\x12\x1f\n" +
	"\x03ref\x18\x01 \x01(\v2\r.app.AssetRefR\x03ref\x12(\n" +
	"\x06select\x18\x02 \x01(\v2\x10.app.AssetSelectR\x06select\"N\n" +
	"\bAssetRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12)\n" +
	"\x04slug\x18\x04 \x01(\v2\x13.app.AssetRefBySlugH\x00R\x04slugB\x05\n" +
	"\x03key\"Q\n" +
	"\x0eAssetRefBySlug\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.payday.TenantRefR\x06tenant\"\xcb\x02\n" +
	"\vAssetSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12,\n" +
	"\x06tenant\x18\x02 \x01(\v2\x14.payday.TenantSelectR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12,\n" +
	"\x06keeper\x18\b \x01(\v2\x14.payday.HolderSelectR\x06keeper\x12\x1a\n" +
	"\blocation\x18\t \x01(\bR\blocation\x12\x16\n" +
	"\x06listed\x18\n" +
	" \x01(\bR\x06listed\x12!\n" +
	"\fdate_updated\x18\r \x01(\bR\vdateUpdated\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\x81\x04\n" +
	"\x11AssetPatchRequest\x12\x1f\n" +
	"\x03ref\x18\x01 \x01(\v2\r.app.AssetRefR\x03ref\x12)\n" +
	"\x06tenant\x18\x04 \x01(\v2\x11.payday.TenantRefR\x06tenant\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\f \x01(\tR\x04desc\x12:\n" +
	"\x06labels\x18\x0e \x03(\v2\".app.AssetPatchRequest.LabelsEntryR\x06labels\x12)\n" +
	"\x06keeper\x18\x10 \x01(\v2\x11.payday.HolderRefR\x06keeper\x12\x1f\n" +
	"\vkeeper_null\x18\x11 \x01(\bR\n" +
	"keeperNull\x12\x1a\n" +
	"\blocation\x18\x12 \x01(\tR\blocation\x12\x16\n" +
	"\x06listed\x18\x14 \x01(\bR\x06listed\x12=\n" +
	"\fdate_updated\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\vdateUpdated\x12,\n" +
	"\x12date_updated_force\x18\x1b \x01(\bR\x10dateUpdatedForce\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x11AssetApplyRequest\x12\x1f\n" +
	"\x03ref\x18\x01 \x01(\v2\r.app.AssetRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"v\n" +
	"\x10AssetListRequest\x12*\n" +
	"\afilters\x18\x01 \x03(\v2\x10.app.AssetFilterR\afilters\x12\x19\n" +
	"\x04size\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x04size\x12\x1b\n" +
	"\x05after\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05after\"P\n" +
	"\x11AssetListResponse\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".app.AssetR\x05items\x12\x19\n" +
	"\x04next\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04next\"F\n" +
	"\vAssetFilter\x12\x1f\n" +
	"\x03ref\x18\x01 \x01(\v2\r.app.AssetRefR\x03ref\x12\x16\n" +
	"\x06listed\x18\x02 \x01(\bR\x06listed\"k\n" +
	"\x11AssetWatchRequest\x12*\n" +
	"\afilters\x18\x01 \x03(\v2\x10.app.AssetFilterR\afilters\x12*\n" +
	"\rskip_snapshot\x18\x02 \x01(\bB\x05\xaa\x01\x02\b\x02R\fskipSnapshot\"?\n" +
	"\x12AssetWatchResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.app.AssetWatchItemR\x05items\"a\n" +
	"\x0eAssetWatchItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".app.AssetR\x05value\x12\x1d\n" +
	"\x06action\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x06action\"r\n" +
	"\x14AssetTransferRequest\x12\x1f\n" +
	"\x03ref\x18\x01 \x01(\v2\r.app.AssetRefR\x03ref\x12!\n" +
	"\x02to\x18\x02 \x01(\v2\x11.payday.TenantRefR\x02to\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\x90\x03\n" +
	"\fAssetService\x12'\n" +
	"\x03Add\x12\x14.app.AssetAddRequest\x1a\n" +
	".app.Asset\x12'\n" +
	"\x03Get\x12\x14.app.AssetGetRequest\x1a\n" +
	".app.Asset\x12+\n" +
	"\x05Patch\x12\x16.app.AssetPatchRequest\x1a\n" +
	".app.Asset\x12+\n" +
	"\x05Apply\x12\x16.app.AssetApplyRequest\x1a\n" +
	".app.Asset\x12.\n" +
	"\x05Erase\x12\r.app.AssetRef\x1a\x16.google.protobuf.Empty\x125\n" +
	"\x04List\x12\x15.app.AssetListRequest\x1a\x16.app.AssetListResponse\x12:\n" +
	"\x05Watch\x12\x16.app.AssetWatchRequest\x1a\x17.app.AssetWatchResponse0\x01\x121\n" +
	"\bTransfer\x12\x19.app.AssetTransferRequest\x1a\n" +
	".app.AssetB\x1dZ\x1bgithub.com/lesomnus/custodyb\beditionsp\xe8\a"

var file_app_asset_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_app_asset_svc_proto_goTypes = []any{
	(*AssetAddRequest)(nil),       // 0: app.AssetAddRequest
	(*AssetGetRequest)(nil),       // 1: app.AssetGetRequest
	(*AssetRef)(nil),              // 2: app.AssetRef
	(*AssetRefBySlug)(nil),        // 3: app.AssetRefBySlug
	(*AssetSelect)(nil),           // 4: app.AssetSelect
	(*AssetPatchRequest)(nil),     // 5: app.AssetPatchRequest
	(*AssetApplyRequest)(nil),     // 6: app.AssetApplyRequest
	(*AssetListRequest)(nil),      // 7: app.AssetListRequest
	(*AssetListResponse)(nil),     // 8: app.AssetListResponse
	(*AssetFilter)(nil),           // 9: app.AssetFilter
	(*AssetWatchRequest)(nil),     // 10: app.AssetWatchRequest
	(*AssetWatchResponse)(nil),    // 11: app.AssetWatchResponse
	(*AssetWatchItem)(nil),        // 12: app.AssetWatchItem
	(*AssetTransferRequest)(nil),  // 13: app.AssetTransferRequest
	nil,                           // 14: app.AssetAddRequest.LabelsEntry
	nil,                           // 15: app.AssetPatchRequest.LabelsEntry
	(*TenantRef)(nil),             // 16: payday.TenantRef
	(*HolderRef)(nil),             // 17: payday.HolderRef
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*TenantSelect)(nil),          // 19: payday.TenantSelect
	(*HolderSelect)(nil),          // 20: payday.HolderSelect
	(*patchpb.Patch)(nil),         // 21: patch.Patch
	(*Asset)(nil),                 // 22: app.Asset
	(*emptypb.Empty)(nil),         // 23: google.protobuf.Empty
}
var file_app_asset_svc_proto_depIdxs = []int32{
	16, // 0: app.AssetAddRequest.tenant:type_name -> payday.TenantRef
	14, // 1: app.AssetAddRequest.labels:type_name -> app.AssetAddRequest.LabelsEntry
	17, // 2: app.AssetAddRequest.keeper:type_name -> payday.HolderRef
	18, // 3: app.AssetAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 4: app.AssetGetRequest.ref:type_name -> app.AssetRef
	4,  // 5: app.AssetGetRequest.select:type_name -> app.AssetSelect
	3,  // 6: app.AssetRef.slug:type_name -> app.AssetRefBySlug
	16, // 7: app.AssetRefBySlug.tenant:type_name -> payday.TenantRef
	19, // 8: app.AssetSelect.tenant:type_name -> payday.TenantSelect
	20, // 9: app.AssetSelect.keeper:type_name -> payday.HolderSelect
	2,  // 10: app.AssetPatchRequest.ref:type_name -> app.AssetRef
	16, // 11: app.AssetPatchRequest.tenant:type_name -> payday.TenantRef
	15, // 12: app.AssetPatchRequest.labels:type_name -> app.AssetPatchRequest.LabelsEntry
	17, // 13: app.AssetPatchRequest.keeper:type_name -> payday.HolderRef
	18, // 14: app.AssetPatchRequest.date_updated:type_name -> google.protobuf.Timestamp
	2,  // 15: app.AssetApplyRequest.ref:type_name -> app.AssetRef
	21, // 16: app.AssetApplyRequest.patch:type_name -> patch.Patch
	9,  // 17: app.AssetListRequest.filters:type_name -> app.AssetFilter
	22, // 18: app.AssetListResponse.items:type_name -> app.Asset
	2,  // 19: app.AssetFilter.ref:type_name -> app.AssetRef
	9,  // 20: app.AssetWatchRequest.filters:type_name -> app.AssetFilter
	12, // 21: app.AssetWatchResponse.items:type_name -> app.AssetWatchItem
	22, // 22: app.AssetWatchItem.value:type_name -> app.Asset
	2,  // 23: app.AssetTransferRequest.ref:type_name -> app.AssetRef
	16, // 24: app.AssetTransferRequest.to:type_name -> payday.TenantRef
	0,  // 25: app.AssetService.Add:input_type -> app.AssetAddRequest
	1,  // 26: app.AssetService.Get:input_type -> app.AssetGetRequest
	5,  // 27: app.AssetService.Patch:input_type -> app.AssetPatchRequest
	6,  // 28: app.AssetService.Apply:input_type -> app.AssetApplyRequest
	2,  // 29: app.AssetService.Erase:input_type -> app.AssetRef
	7,  // 30: app.AssetService.List:input_type -> app.AssetListRequest
	10, // 31: app.AssetService.Watch:input_type -> app.AssetWatchRequest
	13, // 32: app.AssetService.Transfer:input_type -> app.AssetTransferRequest
	22, // 33: app.AssetService.Add:output_type -> app.Asset
	22, // 34: app.AssetService.Get:output_type -> app.Asset
	22, // 35: app.AssetService.Patch:output_type -> app.Asset
	22, // 36: app.AssetService.Apply:output_type -> app.Asset
	23, // 37: app.AssetService.Erase:output_type -> google.protobuf.Empty
	8,  // 38: app.AssetService.List:output_type -> app.AssetListResponse
	11, // 39: app.AssetService.Watch:output_type -> app.AssetWatchResponse
	22, // 40: app.AssetService.Transfer:output_type -> app.Asset
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_app_asset_svc_proto_init() }
func file_app_asset_svc_proto_init() {
	if File_app_asset_svc_proto != nil {
		return
	}
	file_app_asset_proto_init()
	file_payday_holder_svc_proto_init()
	file_payday_tenant_svc_proto_init()
	file_app_asset_svc_proto_msgTypes[2].OneofWrappers = []any{
		(*assetRef_Id)(nil),
		(*assetRef_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_asset_svc_proto_rawDesc), len(file_app_asset_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_asset_svc_proto_goTypes,
		DependencyIndexes: file_app_asset_svc_proto_depIdxs,
		MessageInfos:      file_app_asset_svc_proto_msgTypes,
	}.Build()
	File_app_asset_svc_proto = out.File
	file_app_asset_svc_proto_goTypes = nil
	file_app_asset_svc_proto_depIdxs = nil
}
