// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: app/asset_svc.proto

package custody

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_Add_FullMethodName      = "/app.AssetService/Add"
	AssetService_Get_FullMethodName      = "/app.AssetService/Get"
	AssetService_Patch_FullMethodName    = "/app.AssetService/Patch"
	AssetService_Apply_FullMethodName    = "/app.AssetService/Apply"
	AssetService_Erase_FullMethodName    = "/app.AssetService/Erase"
	AssetService_List_FullMethodName     = "/app.AssetService/List"
	AssetService_Watch_FullMethodName    = "/app.AssetService/Watch"
	AssetService_Transfer_FullMethodName = "/app.AssetService/Transfer"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetServiceClient interface {
	// Add creates a new Asset
	Add(ctx context.Context, in *AssetAddRequest, opts ...grpc.CallOption) (*Asset, error)
	// Get retrieves a Asset
	Get(ctx context.Context, in *AssetGetRequest, opts ...grpc.CallOption) (*Asset, error)
	// Patch updates an existing Asset
	Patch(ctx context.Context, in *AssetPatchRequest, opts ...grpc.CallOption) (*Asset, error)
	// Apply applies a patch document to an existing Asset
	Apply(ctx context.Context, in *AssetApplyRequest, opts ...grpc.CallOption) (*Asset, error)
	// Erase deletes a Asset
	Erase(ctx context.Context, in *AssetRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List reads Assets a page at a time.
	List(ctx context.Context, in *AssetListRequest, opts ...grpc.CallOption) (*AssetListResponse, error)
	// Watch the Assets this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *AssetWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssetWatchResponse], error)
	// Transfer moves an asset from the tenant that holds it to another.
	//
	// # Why it cannot be a Patch
	//
	// `Asset.tenant` is mutable, so `Patch` could set it. That is exactly why
	// `Patch` and `Apply` are closed to callers: they write any field the schema
	// has, so a rule attached to one field is a rule a general write walks past.
	// This is where the rule lives, and closing the general writes is what makes
	// it the only door.
	//
	// # Three things happen and only the first is a write
	//
	//   - the asset changes tenant, so it leaves the wall it was behind;
	//   - the keeper is cleared, because being answerable for something does not
	//     travel with it -- that person is in the tenant it left;
	//   - and the trail stays behind. `Audit` stamps the tenant of the **actor**,
	//     so the receiving tenant reads what has happened since it arrived and
	//     nothing before. That is payday's decision rather than this app's, and
	//     `payday/audit.proto` writes it out: receiving something does not come
	//     with the right to read what its previous owner did inside their own
	//     walls.
	Transfer(ctx context.Context, in *AssetTransferRequest, opts ...grpc.CallOption) (*Asset, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) Add(ctx context.Context, in *AssetAddRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Get(ctx context.Context, in *AssetGetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Patch(ctx context.Context, in *AssetPatchRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Apply(ctx context.Context, in *AssetApplyRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Erase(ctx context.Context, in *AssetRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AssetService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) List(ctx context.Context, in *AssetListRequest, opts ...grpc.CallOption) (*AssetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetListResponse)
	err := c.cc.Invoke(ctx, AssetService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Watch(ctx context.Context, in *AssetWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssetWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AssetService_ServiceDesc.Streams[0], AssetService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssetWatchRequest, AssetWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_WatchClient = grpc.ServerStreamingClient[AssetWatchResponse]

func (c *assetServiceClient) Transfer(ctx context.Context, in *AssetTransferRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
type AssetServiceServer interface {
	// Add creates a new Asset
	Add(context.Context, *AssetAddRequest) (*Asset, error)
	// Get retrieves a Asset
	Get(context.Context, *AssetGetRequest) (*Asset, error)
	// Patch updates an existing Asset
	Patch(context.Context, *AssetPatchRequest) (*Asset, error)
	// Apply applies a patch document to an existing Asset
	Apply(context.Context, *AssetApplyRequest) (*Asset, error)
	// Erase deletes a Asset
	Erase(context.Context, *AssetRef) (*emptypb.Empty, error)
	// List reads Assets a page at a time.
	List(context.Context, *AssetListRequest) (*AssetListResponse, error)
	// Watch the Assets this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(*AssetWatchRequest, grpc.ServerStreamingServer[AssetWatchResponse]) error
	// Transfer moves an asset from the tenant that holds it to another.
	//
	// # Why it cannot be a Patch
	//
	// `Asset.tenant` is mutable, so `Patch` could set it. That is exactly why
	// `Patch` and `Apply` are closed to callers: they write any field the schema
	// has, so a rule attached to one field is a rule a general write walks past.
	// This is where the rule lives, and closing the general writes is what makes
	// it the only door.
	//
	// # Three things happen and only the first is a write
	//
	//   - the asset changes tenant, so it leaves the wall it was behind;
	//   - the keeper is cleared, because being answerable for something does not
	//     travel with it -- that person is in the tenant it left;
	//   - and the trail stays behind. `Audit` stamps the tenant of the **actor**,
	//     so the receiving tenant reads what has happened since it arrived and
	//     nothing before. That is payday's decision rather than this app's, and
	//     `payday/audit.proto` writes it out: receiving something does not come
	//     with the right to read what its previous owner did inside their own
	//     walls.
	Transfer(context.Context, *AssetTransferRequest) (*Asset, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) Add(context.Context, *AssetAddRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAssetServiceServer) Get(context.Context, *AssetGetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAssetServiceServer) Patch(context.Context, *AssetPatchRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedAssetServiceServer) Apply(context.Context, *AssetApplyRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedAssetServiceServer) Erase(context.Context, *AssetRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedAssetServiceServer) List(context.Context, *AssetListRequest) (*AssetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAssetServiceServer) Watch(*AssetWatchRequest, grpc.ServerStreamingServer[AssetWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAssetServiceServer) Transfer(context.Context, *AssetTransferRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Add(ctx, req.(*AssetAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Get(ctx, req.(*AssetGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Patch(ctx, req.(*AssetPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Apply(ctx, req.(*AssetApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Erase(ctx, req.(*AssetRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).List(ctx, req.(*AssetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AssetWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssetServiceServer).Watch(m, &grpc.GenericServerStream[AssetWatchRequest, AssetWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_WatchServer = grpc.ServerStreamingServer[AssetWatchResponse]

func _AssetService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Transfer(ctx, req.(*AssetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AssetService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AssetService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _AssetService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _AssetService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _AssetService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AssetService_List_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _AssetService_Transfer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _AssetService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app/asset_svc.proto",
}
