// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: app/catalogue.proto

package custody

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogueService_Search_FullMethodName = "/app.CatalogueService/Search"
)

// CatalogueServiceClient is the client API for CatalogueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CatalogueService is what anybody may read, and it is a **different message**
// rather than the asset without a wall.
//
// That distinction is the point of it being here. Making `Asset` publicly
// readable at the schema level would publish every field it has -- and nobody
// wants the location and the keeper published. So what is public is a different
// shape of the same row, and a different shape is a different message, which is
// a different RPC.
//
// What that buys, said plainly:
//
//   - the walled path keeps no hole. `Asset.Get` narrows as it always did, and
//     there is no flag anywhere that turns it off;
//   - the projection is written down, so a field added to `Asset` tomorrow is
//     not published by having been forgotten;
//   - and "which rows are public" is this app's predicate, in this app's code,
//     beside the rule that says who may set `listed`.
//
// It is served without a frame -- there is nobody asking -- so it runs against
// a server the wall was never installed on, and every narrowing it does is its
// own. That is the one place in this app where that is true, and it is one
// short file for exactly that reason.
type CatalogueServiceClient interface {
	Search(ctx context.Context, in *CatalogueSearchRequest, opts ...grpc.CallOption) (*CatalogueSearchResponse, error)
}

type catalogueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogueServiceClient(cc grpc.ClientConnInterface) CatalogueServiceClient {
	return &catalogueServiceClient{cc}
}

func (c *catalogueServiceClient) Search(ctx context.Context, in *CatalogueSearchRequest, opts ...grpc.CallOption) (*CatalogueSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogueSearchResponse)
	err := c.cc.Invoke(ctx, CatalogueService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogueServiceServer is the server API for CatalogueService service.
// All implementations must embed UnimplementedCatalogueServiceServer
// for forward compatibility.
//
// CatalogueService is what anybody may read, and it is a **different message**
// rather than the asset without a wall.
//
// That distinction is the point of it being here. Making `Asset` publicly
// readable at the schema level would publish every field it has -- and nobody
// wants the location and the keeper published. So what is public is a different
// shape of the same row, and a different shape is a different message, which is
// a different RPC.
//
// What that buys, said plainly:
//
//   - the walled path keeps no hole. `Asset.Get` narrows as it always did, and
//     there is no flag anywhere that turns it off;
//   - the projection is written down, so a field added to `Asset` tomorrow is
//     not published by having been forgotten;
//   - and "which rows are public" is this app's predicate, in this app's code,
//     beside the rule that says who may set `listed`.
//
// It is served without a frame -- there is nobody asking -- so it runs against
// a server the wall was never installed on, and every narrowing it does is its
// own. That is the one place in this app where that is true, and it is one
// short file for exactly that reason.
type CatalogueServiceServer interface {
	Search(context.Context, *CatalogueSearchRequest) (*CatalogueSearchResponse, error)
	mustEmbedUnimplementedCatalogueServiceServer()
}

// UnimplementedCatalogueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogueServiceServer struct{}

func (UnimplementedCatalogueServiceServer) Search(context.Context, *CatalogueSearchRequest) (*CatalogueSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCatalogueServiceServer) mustEmbedUnimplementedCatalogueServiceServer() {}
func (UnimplementedCatalogueServiceServer) testEmbeddedByValue()                          {}

// UnsafeCatalogueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogueServiceServer will
// result in compilation errors.
type UnsafeCatalogueServiceServer interface {
	mustEmbedUnimplementedCatalogueServiceServer()
}

func RegisterCatalogueServiceServer(s grpc.ServiceRegistrar, srv CatalogueServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogueService_ServiceDesc, srv)
}

func _CatalogueService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogueSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogueServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogueService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogueServiceServer).Search(ctx, req.(*CatalogueSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogueService_ServiceDesc is the grpc.ServiceDesc for CatalogueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.CatalogueService",
	HandlerType: (*CatalogueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _CatalogueService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/catalogue.proto",
}
