// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/asset.proto

package schema

import (
	ent "entgo.io/ent"
	entsql "entgo.io/ent/dialect/entsql"
	schema "entgo.io/ent/schema"
	edge "entgo.io/ent/schema/edge"
	field "entgo.io/ent/schema/field"
	index "entgo.io/ent/schema/index"
	uuid "github.com/google/uuid"
)

type Asset struct {
	ent.Schema
}

func (Asset) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias"),
		field.String("name"),
		field.String("desc"),
		field.JSON("labels", map[string]string{}).
			Optional(),
		field.String("location"),
		field.Bool("listed"),
		field.Time("date_updated"),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}

func (Asset) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Required(),
		edge.To("keeper", Holder.Type).
			Unique(),
	}
}

func (Asset) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("date_created", "id"),
		index.Fields("alias").
			Edges("tenant").
			Unique(),
		index.Fields("listed", "date_created"),
	}
}

func (Asset) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "asset"},
	}
}
