// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AssetColumns holds the columns for the "asset" table.
	AssetColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "location", Type: field.TypeString},
		{Name: "listed", Type: field.TypeBool},
		{Name: "date_updated", Type: field.TypeTime},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
		{Name: "asset_tenant", Type: field.TypeUUID},
		{Name: "asset_keeper", Type: field.TypeUUID, Nullable: true},
	}
	// AssetTable holds the schema information for the "asset" table.
	AssetTable = &schema.Table{
		Name:       "asset",
		Columns:    AssetColumns,
		PrimaryKey: []*schema.Column{AssetColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "asset_tenant_tenant",
				Columns:    []*schema.Column{AssetColumns[9]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "asset_holder_keeper",
				Columns:    []*schema.Column{AssetColumns[10]},
				RefColumns: []*schema.Column{HolderColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "asset_date_created_id",
				Unique:  false,
				Columns: []*schema.Column{AssetColumns[8], AssetColumns[0]},
			},
			{
				Name:    "asset_alias_asset_tenant",
				Unique:  true,
				Columns: []*schema.Column{AssetColumns[1], AssetColumns[9]},
			},
			{
				Name:    "asset_listed_date_created",
				Unique:  false,
				Columns: []*schema.Column{AssetColumns[6], AssetColumns[8]},
			},
		},
	}
	// AuditColumns holds the columns for the "audit" table.
	AuditColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "trace_id", Type: field.TypeBytes},
		{Name: "action", Type: field.TypeString},
		{Name: "object_id", Type: field.TypeUUID},
		{Name: "patch", Type: field.TypeBytes},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// AuditTable holds the schema information for the "audit" table.
	AuditTable = &schema.Table{
		Name:       "audit",
		Columns:    AuditColumns,
		PrimaryKey: []*schema.Column{AuditColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "audit_object_id",
				Unique:  false,
				Columns: []*schema.Column{AuditColumns[5]},
			},
			{
				Name:    "audit_tenant_id_date_created",
				Unique:  false,
				Columns: []*schema.Column{AuditColumns[1], AuditColumns[7]},
			},
		},
	}
	// HolderColumns holds the columns for the "holder" table.
	HolderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_updated", Type: field.TypeTime},
		{Name: "date_erased", Type: field.TypeTime, Nullable: true},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
		{Name: "idp_subject", Type: field.TypeString, Nullable: true},
		{Name: "holder_tenant", Type: field.TypeUUID},
	}
	// HolderTable holds the schema information for the "holder" table.
	HolderTable = &schema.Table{
		Name:       "holder",
		Columns:    HolderColumns,
		PrimaryKey: []*schema.Column{HolderColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "holder_tenant_tenant",
				Columns:    []*schema.Column{HolderColumns[9]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "holder_alias_holder_tenant",
				Unique:  true,
				Columns: []*schema.Column{HolderColumns[1], HolderColumns[9]},
				Annotation: &entsql.IndexAnnotation{
					Where: "date_erased IS NULL",
				},
			},
			{
				Name:    "holder_idp_subject",
				Unique:  true,
				Columns: []*schema.Column{HolderColumns[8]},
				Annotation: &entsql.IndexAnnotation{
					Where: "date_erased IS NULL",
				},
			},
		},
	}
	// OutboxColumns holds the columns for the "outbox" table.
	OutboxColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "method", Type: field.TypeString},
		{Name: "by", Type: field.TypeString},
		{Name: "object_id", Type: field.TypeUUID},
		{Name: "patch", Type: field.TypeBytes},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// OutboxTable holds the schema information for the "outbox" table.
	OutboxTable = &schema.Table{
		Name:       "outbox",
		Columns:    OutboxColumns,
		PrimaryKey: []*schema.Column{OutboxColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outbox_id",
				Unique:  false,
				Columns: []*schema.Column{OutboxColumns[0]},
			},
		},
	}
	// TenantColumns holds the columns for the "tenant" table.
	TenantColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_updated", Type: field.TypeTime},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// TenantTable holds the schema information for the "tenant" table.
	TenantTable = &schema.Table{
		Name:       "tenant",
		Columns:    TenantColumns,
		PrimaryKey: []*schema.Column{TenantColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AssetTable,
		AuditTable,
		HolderTable,
		OutboxTable,
		TenantTable,
	}
)

func init() {
	AssetTable.ForeignKeys[0].RefTable = TenantTable
	AssetTable.ForeignKeys[1].RefTable = HolderTable
	AssetTable.Annotation = &entsql.Annotation{
		Table: "asset",
	}
	AuditTable.Annotation = &entsql.Annotation{
		Table: "audit",
	}
	HolderTable.ForeignKeys[0].RefTable = TenantTable
	HolderTable.Annotation = &entsql.Annotation{
		Table: "holder",
	}
	OutboxTable.Annotation = &entsql.Annotation{
		Table: "outbox",
	}
	TenantTable.Annotation = &entsql.Annotation{
		Table: "tenant",
	}
}
