// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lesomnus/custody/internal/ent/asset"
	"github.com/lesomnus/custody/internal/ent/holder"
	"github.com/lesomnus/custody/internal/ent/tenant"
)

// AssetCreate is the builder for creating a Asset entity.
type AssetCreate struct {
	config
	mutation *AssetMutation
	hooks    []Hook
}

// SetAlias sets the "alias" field.
func (_c *AssetCreate) SetAlias(v string) *AssetCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AssetCreate) SetName(v string) *AssetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *AssetCreate) SetDesc(v string) *AssetCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetLabels sets the "labels" field.
func (_c *AssetCreate) SetLabels(v map[string]string) *AssetCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetLocation sets the "location" field.
func (_c *AssetCreate) SetLocation(v string) *AssetCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetListed sets the "listed" field.
func (_c *AssetCreate) SetListed(v bool) *AssetCreate {
	_c.mutation.SetListed(v)
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *AssetCreate) SetDateUpdated(v time.Time) *AssetCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *AssetCreate) SetDateCreated(v time.Time) *AssetCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *AssetCreate) SetNillableDateCreated(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *AssetCreate) SetTenantID(v uuid.UUID) *AssetCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetKeeperID sets the "keeper_id" field.
func (_c *AssetCreate) SetKeeperID(v uuid.UUID) *AssetCreate {
	_c.mutation.SetKeeperID(v)
	return _c
}

// SetNillableKeeperID sets the "keeper_id" field if the given value is not nil.
func (_c *AssetCreate) SetNillableKeeperID(v *uuid.UUID) *AssetCreate {
	if v != nil {
		_c.SetKeeperID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AssetCreate) SetID(v uuid.UUID) *AssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *AssetCreate) SetTenant(v *Tenant) *AssetCreate {
	return _c.SetTenantID(v.ID)
}

// SetKeeper sets the "keeper" edge to the Holder entity.
func (_c *AssetCreate) SetKeeper(v *Holder) *AssetCreate {
	return _c.SetKeeperID(v.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (_c *AssetCreate) Mutation() *AssetMutation {
	return _c.mutation
}

// Save creates the Asset in the database.
func (_c *AssetCreate) Save(ctx context.Context) (*Asset, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetCreate) SaveX(ctx context.Context) *Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetCreate) check() error {
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Asset.alias"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Asset.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "Asset.desc"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "Asset.location"`)}
	}
	if _, ok := _c.mutation.Listed(); !ok {
		return &ValidationError{Name: "listed", err: errors.New(`ent: missing required field "Asset.listed"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "Asset.date_updated"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Asset.tenant_id"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Asset.tenant"`)}
	}
	return nil
}

func (_c *AssetCreate) sqlSave(ctx context.Context) (*Asset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetCreate) createSpec() (*Asset, *sqlgraph.CreateSpec) {
	var (
		_node = &Asset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(asset.Table, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(asset.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(asset.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(asset.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(asset.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(asset.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Listed(); ok {
		_spec.SetField(asset.FieldListed, field.TypeBool, value)
		_node.Listed = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(asset.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(asset.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.KeeperIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.KeeperTable,
			Columns: []string{asset.KeeperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(holder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.KeeperID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssetCreateBulk is the builder for creating many Asset entities in bulk.
type AssetCreateBulk struct {
	config
	err      error
	builders []*AssetCreate
}

// Save creates the Asset entities in the database.
func (_c *AssetCreateBulk) Save(ctx context.Context) ([]*Asset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Asset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetCreateBulk) SaveX(ctx context.Context) []*Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
