// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/asset.proto

package ent

import (
	custody "github.com/lesomnus/custody"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Asset) Proto() *custody.Asset {
	x := &custody.Asset{}
	x.SetId(e.ID[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	}
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	if v := e.Edges.Keeper; v != nil {
		x.SetKeeper(v.Proto())
	}
	x.SetLocation(e.Location)
	x.SetListed(e.Listed)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
