// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lesomnus/custody/internal/ent/asset"
	"github.com/lesomnus/custody/internal/ent/holder"
	"github.com/lesomnus/custody/internal/ent/predicate"
	"github.com/lesomnus/custody/internal/ent/tenant"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks     []Hook
	mutation  *AssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *AssetUpdate) SetAlias(v string) *AssetUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableAlias(v *string) *AssetUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AssetUpdate) SetName(v string) *AssetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableName(v *string) *AssetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *AssetUpdate) SetDesc(v string) *AssetUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableDesc(v *string) *AssetUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *AssetUpdate) SetLabels(v map[string]string) *AssetUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *AssetUpdate) ClearLabels() *AssetUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetLocation sets the "location" field.
func (_u *AssetUpdate) SetLocation(v string) *AssetUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableLocation(v *string) *AssetUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetListed sets the "listed" field.
func (_u *AssetUpdate) SetListed(v bool) *AssetUpdate {
	_u.mutation.SetListed(v)
	return _u
}

// SetNillableListed sets the "listed" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableListed(v *bool) *AssetUpdate {
	if v != nil {
		_u.SetListed(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *AssetUpdate) SetDateUpdated(v time.Time) *AssetUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableDateUpdated(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *AssetUpdate) SetTenantID(id uuid.UUID) *AssetUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *AssetUpdate) SetTenant(v *Tenant) *AssetUpdate {
	return _u.SetTenantID(v.ID)
}

// SetKeeperID sets the "keeper" edge to the Holder entity by ID.
func (_u *AssetUpdate) SetKeeperID(id uuid.UUID) *AssetUpdate {
	_u.mutation.SetKeeperID(id)
	return _u
}

// SetNillableKeeperID sets the "keeper" edge to the Holder entity by ID if the given value is not nil.
func (_u *AssetUpdate) SetNillableKeeperID(id *uuid.UUID) *AssetUpdate {
	if id != nil {
		_u = _u.SetKeeperID(*id)
	}
	return _u
}

// SetKeeper sets the "keeper" edge to the Holder entity.
func (_u *AssetUpdate) SetKeeper(v *Holder) *AssetUpdate {
	return _u.SetKeeperID(v.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *AssetUpdate) ClearTenant() *AssetUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearKeeper clears the "keeper" edge to the Holder entity.
func (_u *AssetUpdate) ClearKeeper() *AssetUpdate {
	_u.mutation.ClearKeeper()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AssetUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AssetUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(asset.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(asset.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(asset.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(asset.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(asset.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(asset.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Listed(); ok {
		_spec.SetField(asset.FieldListed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(asset.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(asset.FieldDateCreated, field.TypeTime)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeeperCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.KeeperTable,
			Columns: []string{asset.KeeperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(holder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeeperIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.KeeperTable,
			Columns: []string{asset.KeeperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(holder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAlias sets the "alias" field.
func (_u *AssetUpdateOne) SetAlias(v string) *AssetUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableAlias(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AssetUpdateOne) SetName(v string) *AssetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableName(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *AssetUpdateOne) SetDesc(v string) *AssetUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableDesc(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *AssetUpdateOne) SetLabels(v map[string]string) *AssetUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *AssetUpdateOne) ClearLabels() *AssetUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetLocation sets the "location" field.
func (_u *AssetUpdateOne) SetLocation(v string) *AssetUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableLocation(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetListed sets the "listed" field.
func (_u *AssetUpdateOne) SetListed(v bool) *AssetUpdateOne {
	_u.mutation.SetListed(v)
	return _u
}

// SetNillableListed sets the "listed" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableListed(v *bool) *AssetUpdateOne {
	if v != nil {
		_u.SetListed(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *AssetUpdateOne) SetDateUpdated(v time.Time) *AssetUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableDateUpdated(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *AssetUpdateOne) SetTenantID(id uuid.UUID) *AssetUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *AssetUpdateOne) SetTenant(v *Tenant) *AssetUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetKeeperID sets the "keeper" edge to the Holder entity by ID.
func (_u *AssetUpdateOne) SetKeeperID(id uuid.UUID) *AssetUpdateOne {
	_u.mutation.SetKeeperID(id)
	return _u
}

// SetNillableKeeperID sets the "keeper" edge to the Holder entity by ID if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableKeeperID(id *uuid.UUID) *AssetUpdateOne {
	if id != nil {
		_u = _u.SetKeeperID(*id)
	}
	return _u
}

// SetKeeper sets the "keeper" edge to the Holder entity.
func (_u *AssetUpdateOne) SetKeeper(v *Holder) *AssetUpdateOne {
	return _u.SetKeeperID(v.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *AssetUpdateOne) ClearTenant() *AssetUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearKeeper clears the "keeper" edge to the Holder entity.
func (_u *AssetUpdateOne) ClearKeeper() *AssetUpdateOne {
	_u.mutation.ClearKeeper()
	return _u
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AssetUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AssetUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(asset.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(asset.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(asset.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(asset.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(asset.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(asset.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Listed(); ok {
		_spec.SetField(asset.FieldListed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(asset.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(asset.FieldDateCreated, field.TypeTime)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeeperCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.KeeperTable,
			Columns: []string{asset.KeeperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(holder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeeperIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.KeeperTable,
			Columns: []string{asset.KeeperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(holder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
