// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/payday/holder.proto

package ent

import (
	uuid "github.com/google/uuid"
	api "github.com/lesomnus/custody/api"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Holder) Proto() *api.Holder {
	x := &api.Holder{}
	x.SetId(e.ID[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	} else if v := e.TenantID; v != *new(uuid.UUID) {
		r := &api.Tenant{}
		r.SetId(v[:])
		x.SetTenant(r)
	}
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
