// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: payday/holder.proto

package ent

import (
	api "github.com/lesomnus/custody/api"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Holder) Proto() *api.Holder {
	x := &api.Holder{}
	x.SetId(e.ID[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	}
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	if e.IdpSubject != nil {
		x.SetIdpSubject(*e.IdpSubject)
	}
	return x
}
