// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/payday/outbox.proto

package ent

import (
	api "github.com/lesomnus/custody/api"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Outbox) Proto() *api.Outbox {
	x := &api.Outbox{}
	x.SetId(e.ID[:])
	x.SetTenantId(e.TenantID[:])
	x.SetActorId(e.ActorID[:])
	x.SetMethod(e.Method)
	x.SetBy(e.By)
	x.SetObjectId(e.ObjectID[:])
	x.SetPatch(e.Patch)
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
