// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: payday/tenant.proto

package ent

import (
	custody "github.com/lesomnus/custody"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Tenant) Proto() *custody.Tenant {
	x := &custody.Tenant{}
	x.SetId(e.ID[:])
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
