// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// Holder is the predicate function for holder builders.
type Holder func(*sql.Selector)

// Outbox is the predicate function for outbox builders.
type Outbox func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)
