// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/asset.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	uuid "github.com/google/uuid"
	api "github.com/lesomnus/custody/api"
	ent "github.com/lesomnus/custody/internal/ent"
	asset "github.com/lesomnus/custody/internal/ent/asset"
	predicate "github.com/lesomnus/custody/internal/ent/predicate"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	graph "github.com/protobuf-orm/protobuf-orm/graph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	time "time"
)

type AssetServiceServer struct {
	Store

	api.UnimplementedAssetServiceServer
}

// NewAssetServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewAssetServiceServer(db *ent.Client, opts ...Option) api.AssetServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return AssetServiceServer{Store: s.Store}
}

// AssetNarrow answers with `p` and everything else that narrows a
// read of a Asset: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func AssetNarrow(ctx context.Context, scope Scope, p predicate.Asset) (predicate.Asset, error) {
	ps := make([]predicate.Asset, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, asset.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.AssetScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return asset.And(ps...), nil
	}
}

// narrow is [AssetNarrow] with this server's own scope.
func (s AssetServiceServer) narrow(ctx context.Context, p predicate.Asset) (predicate.Asset, error) {
	return AssetNarrow(ctx, s.Scope, p)
}

func (s AssetServiceServer) Add(ctx context.Context, req *api.AssetAddRequest) (*api.Asset, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *api.Asset), 0, 2)
	q := st.Db.Asset.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Asset", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantID(k)
		ds = append(ds, func(v *api.Asset) {
			v.SetTenant(api.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasKeeper() {
		if k, err := HolderGetKey(ctx, st.Db, req.GetKeeper()); err != nil {
			return nil, err
		} else {
			q.SetKeeperID(k)
			ds = append(ds, func(v *api.Asset) {
				v.SetKeeper(api.Holder_builder{Id: k[:]}.Build())
			})
		}
	}
	q.SetLocation(req.GetLocation())
	q.SetListed(req.GetListed())
	q.SetDateUpdated(time.Now().UTC())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(time.Now().UTC())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "Asset already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "Asset: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  api.AssetService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s AssetServiceServer) Get(ctx context.Context, req *api.AssetGetRequest) (*api.Asset, error) {
	p, err := AssetPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Asset.Query().Where(p)
	AssetSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Asset not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectAssetKey(q *ent.AssetQuery) {
	q.Select(asset.FieldID)
}

func AssetSelectedFields(m *api.AssetSelect) []string {
	if m.GetAll() {
		return asset.Columns
	}

	vs := make([]string, 0, len(asset.Columns))
	{
		vs = append(vs, asset.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, asset.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, asset.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, asset.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, asset.FieldLabels)
	}
	if m.GetLocation() {
		vs = append(vs, asset.FieldLocation)
	}
	if m.GetListed() {
		vs = append(vs, asset.FieldListed)
	}
	if m.GetDateUpdated() {
		vs = append(vs, asset.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, asset.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, asset.FieldDateCreated)
	}

	return vs
}

func AssetSelect(q *ent.AssetQuery, m *api.AssetSelect) {
	if !m.GetAll() {
		fields := AssetSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
	if m.HasKeeper() {
		q.WithKeeper(func(q *ent.HolderQuery) {
			HolderSelect(q, m.GetKeeper())
		})
	}
}

func AssetSelectInit(q *ent.AssetQuery, m *api.AssetSelect) {
	if m != nil {
		AssetSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
		q.WithKeeper(selectHolderKey)
	}
}

func (s AssetServiceServer) Patch(ctx context.Context, req *api.AssetPatchRequest) (*api.Asset, error) {
	doc, err := ormpatch.FromPatchRequest(assetOrmEntity, req.ProtoReflect(), func(ed graph.Edge, ref protoreflect.Message) (protoreflect.Value, error) {
		switch ed.Number() {
		case 2:
			k, err := TenantGetKey(ctx, s.Db, ref.Interface().(*api.TenantRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		case 8:
			k, err := HolderGetKey(ctx, s.Db, ref.Interface().(*api.HolderRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		}
		return protoreflect.Value{}, status.Errorf(codes.Internal, "no key resolver for edge: %s", ed.Name())
	})
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, api.AssetService_Patch_FullMethodName)
}

func AssetGetKey(ctx context.Context, db *ent.Client, ref *api.AssetRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := AssetPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Asset.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Asset not found")
		}
		return z, err
	}

	return v, nil
}

var assetOrmEntity = ormpatch.MustEntityOf(api.File_app_asset_proto, "Asset")

var assetPatchColumns = entpatch.Columns{
	1: asset.FieldID, 2: asset.TenantColumn, 4: asset.FieldAlias, 5: asset.FieldName, 6: asset.FieldDesc, 7: asset.FieldLabels, 8: asset.KeeperColumn, 9: asset.FieldLocation, 10: asset.FieldListed, 13: asset.FieldDateUpdated, 14: asset.FieldDateErased, 15: asset.FieldDateCreated}

func (s AssetServiceServer) Apply(ctx context.Context, req *api.AssetApplyRequest) (*api.Asset, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), api.AssetService_Apply_FullMethodName)
}

func (s AssetServiceServer) apply(ctx context.Context, ref *api.AssetRef, doc *patchpb.Patch, by string) (*api.Asset, error) {
	plan := &ormpatch.Plan{Entity: assetOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(assetOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, assetPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := AssetGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &api.AssetRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, asset.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Asset.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Asset(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Asset.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Asset not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Asset.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Asset(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(time.Now().UTC())
		}
		if n, err := q.Save(ctx); err != nil {
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Asset.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Asset not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s AssetServiceServer) Erase(ctx context.Context, req *api.AssetRef) (*emptypb.Empty, error) {
	p, err := AssetPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Asset.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &emptypb.Empty{}, nil
			}
			return nil, err
		}

		k = v
		p = asset.IDEQ(v)
	}

	u := st.Db.Asset.Update().Where(p)
	u.SetDateErased(time.Now().UTC())
	u.SetDateUpdated(time.Now().UTC())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  api.AssetService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func AssetPick(req *api.AssetRef) (predicate.Asset, error) {
	switch req.WhichKey() {
	case api.AssetRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return asset.IDEQ(v), nil
		}
	case api.AssetRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.Asset, 0, 2)
		ps = append(ps, asset.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, asset.HasTenantWith(p))
		}
		return asset.And(ps...), nil
	case api.AssetRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Asset")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
