// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: payday/audit.proto

package ent

import (
	custody "github.com/lesomnus/custody"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Audit) Proto() *custody.Audit {
	x := &custody.Audit{}
	x.SetId(e.ID[:])
	x.SetTenantId(e.TenantID[:])
	x.SetActorId(e.ActorID[:])
	x.SetTraceId(e.TraceID)
	x.SetAction(e.Action)
	x.SetObjectId(e.ObjectID[:])
	x.SetPatch(e.Patch)
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
