// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: app/asset.proto

package api

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Asset is a thing the company owns and somebody is answerable for.
//
// Tangible or not: a laptop, a licence, a domain name, a machine on a factory
// floor. What they have in common is the only thing this schema asserts -- a
// tenant holds it, somebody is responsible for it, and it is somewhere.
type Asset struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Keeper      *Holder                `protobuf:"bytes,8,opt,name=keeper"`
	xxx_hidden_Location    string                 `protobuf:"bytes,9,opt,name=location"`
	xxx_hidden_Listed      bool                   `protobuf:"varint,10,opt,name=listed"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_app_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_app_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Asset) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Asset) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Asset) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Asset) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Asset) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Asset) GetKeeper() *Holder {
	if x != nil {
		return x.xxx_hidden_Keeper
	}
	return nil
}

func (x *Asset) GetLocation() string {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return ""
}

func (x *Asset) GetListed() bool {
	if x != nil {
		return x.xxx_hidden_Listed
	}
	return false
}

func (x *Asset) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Asset) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Asset) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Asset) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Asset) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Asset) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Asset) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Asset) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *Asset) SetKeeper(v *Holder) {
	x.xxx_hidden_Keeper = v
}

func (x *Asset) SetLocation(v string) {
	x.xxx_hidden_Location = v
}

func (x *Asset) SetListed(v bool) {
	x.xxx_hidden_Listed = v
}

func (x *Asset) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Asset) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Asset) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Asset) HasKeeper() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Keeper != nil
}

func (x *Asset) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Asset) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Asset) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Asset) ClearKeeper() {
	x.xxx_hidden_Keeper = nil
}

func (x *Asset) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Asset) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Asset_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// The tenant that holds this asset, and it is **not immutable** -- which is
	// the one line of this schema worth arguing about.
	//
	// Every other entity payday ships marks this edge `immutable: true`, because
	// moving a row between tenants moves it between walls and almost nothing
	// should. An asset is the exception this project exists to explore: a laptop
	// goes from one subsidiary to another, and the row that names it is the same
	// row.
	//
	// Making it mutable has a consequence worth stating rather than discovering.
	// `Patch` and `Apply` can write any field the schema has, so with this edge
	// mutable they can move an asset between tenants -- which is exactly what
	// `Transfer` exists to put rules around. They are closed to callers by
	// default (`grpcx.Closed`), and this app leaves them closed. Opening them
	// would make every rule in `Transfer` optional.
	Tenant *Tenant
	// The asset number, which is what a person writes on a sticker and reads back
	// over a phone. It is the alias, so it is folded and checked on the way in
	// and `@acme/lt-0042` reaches this row.
	Alias  string
	Name   string
	Desc   string
	Labels map[string]string
	// The holder answerable for this asset. An edge rather than a name, because
	// "who is responsible" has to stop being true when that person is gone.
	//
	// It is optional: an asset in a store room is nobody's until it is issued.
	Keeper *Holder
	// Where it is, as a person would say it: "Seoul HQ 7F", "warehouse B, rack
	// 12", "https://console.example.com". Text rather than a structure, because
	// a location that is a structure is a second schema nobody asked for -- and
	// an asset manager that cannot say "on loan to a customer" is one people
	// route around.
	Location string
	// Whether this asset appears in the public catalogue.
	//
	// It does **not** make the row publicly readable. What the catalogue serves
	// is a different message with fewer fields; see `catalogue.proto` for why
	// that is a projection rather than a wall with a hole in it.
	Listed      bool
	DateUpdated *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 Asset_builder) Build() *Asset {
	m0 := &Asset{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Keeper = b.Keeper
	x.xxx_hidden_Location = b.Location
	x.xxx_hidden_Listed = b.Listed
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_asset_proto protoreflect.FileDescriptor

const file_app_asset_proto_rawDesc = "" +
	"\n" +
	"\x0fapp/asset.proto\x12\x03app\x1a\x13payday/holder.proto\x1a\x13payday/tenant.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\x98\x05\n" +
	"\x05Asset\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12,\n" +
	"\x06tenant\x18\x02 \x01(\v2\x0e.payday.TenantB\x04\xf2\x82\x16\x00R\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12.\n" +
	"\x06labels\x18\a \x03(\v2\x16.app.Asset.LabelsEntryR\x06labels\x12.\n" +
	"\x06keeper\x18\b \x01(\v2\x0e.payday.HolderB\x06\xf2\x82\x16\x028\x01R\x06keeper\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x16\n" +
	"\x06listed\x18\n" +
	" \x01(\bR\x06listed\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xa4\x01\xca\xfc\x15o\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a\x1f\x12\x04slug\x1a\t\n" +
	"\x05alias\x10\x04\x1a\n" +
	"\n" +
	"\x06tenant\x10\x020\x01\x1a&\x12\x06listed\x1a\n" +
	"\n" +
	"\x06listed\x10\n" +
	"\x1a\x10\n" +
	"\fdate_created\x10\x0f\x8a\xbb\x16-\b\a2'\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x04\n" +
	"\x02id\x1a\x03ref\x1a\x06listed \x14(d:\x00B&Z\x1fgithub.com/lesomnus/custody/api\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_asset_proto_goTypes = []any{
	(*Asset)(nil),                 // 0: app.Asset
	nil,                           // 1: app.Asset.LabelsEntry
	(*Tenant)(nil),                // 2: payday.Tenant
	(*Holder)(nil),                // 3: payday.Holder
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_app_asset_proto_depIdxs = []int32{
	2, // 0: app.Asset.tenant:type_name -> payday.Tenant
	1, // 1: app.Asset.labels:type_name -> app.Asset.LabelsEntry
	3, // 2: app.Asset.keeper:type_name -> payday.Holder
	4, // 3: app.Asset.date_updated:type_name -> google.protobuf.Timestamp
	4, // 4: app.Asset.date_created:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_asset_proto_init() }
func file_app_asset_proto_init() {
	if File_app_asset_proto != nil {
		return
	}
	file_payday_holder_proto_init()
	file_payday_tenant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_asset_proto_rawDesc), len(file_app_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_asset_proto_goTypes,
		DependencyIndexes: file_app_asset_proto_depIdxs,
		MessageInfos:      file_app_asset_proto_msgTypes,
	}.Build()
	File_app_asset_proto = out.File
	file_app_asset_proto_goTypes = nil
	file_app_asset_proto_depIdxs = nil
}
