// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package api

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *AssetRef) Pick() *AssetGetRequest {
	return AssetGetRequest_builder{Ref: x}.Build()
}

func (x *Asset) Ref() *AssetRef {
	if v := x.GetId(); len(v) > 0 {
		return AssetById(v)
	}
	{
		v1 := x.GetAlias()
		v2 := x.GetTenant()
		if len(v1) > 0 && v2 != nil {
			return AssetBySlug(v1, v2.Ref())
		}
	}

	return nil
}

func (x *Asset) Pick() *AssetGetRequest {
	return x.Ref().Pick()
}

func (x *AssetRef) Picks(v *Asset) bool {
	switch x.WhichKey() {
	case AssetRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case AssetRef_Slug_case:
		x := x.GetSlug()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetTenant().Picks(v.GetTenant()))
	default:
		return false
	}
}

func (x *AssetGetRequest) WithSelect(f func(s *AssetSelect)) *AssetGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&AssetSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Asset) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Asset) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func AssetById(v []byte) *AssetRef {
	x := &AssetRef{}
	x.SetId(v)
	return x
}

func AssetGetById(v []byte) *AssetGetRequest {
	return AssetGetRequest_builder{Ref: AssetById(v)}.Build()
}

func AssetBySlug(alias string, tenant *TenantRef) *AssetRef {
	x := &AssetRefBySlug{}
	x.SetAlias(alias)
	x.SetTenant(tenant)
	return AssetRef_builder{Slug: x}.Build()
}

func AssetGetBySlug(alias string, tenant *TenantRef) *AssetGetRequest {
	return AssetGetRequest_builder{Ref: AssetBySlug(alias, tenant)}.Build()
}
