// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: app/catalogue.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogueSearchRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Next string                 `protobuf:"bytes,1,opt,name=next"`
	xxx_hidden_Size uint32                 `protobuf:"varint,2,opt,name=size"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CatalogueSearchRequest) Reset() {
	*x = CatalogueSearchRequest{}
	mi := &file_app_catalogue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogueSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogueSearchRequest) ProtoMessage() {}

func (x *CatalogueSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_catalogue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatalogueSearchRequest) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *CatalogueSearchRequest) GetSize() uint32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *CatalogueSearchRequest) SetNext(v string) {
	x.xxx_hidden_Next = v
}

func (x *CatalogueSearchRequest) SetSize(v uint32) {
	x.xxx_hidden_Size = v
}

type CatalogueSearchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A page, in the same words a generated List takes one: nothing means the
	// first, and what comes back says how to ask for the next.
	Next string
	Size uint32
}

func (b0 CatalogueSearchRequest_builder) Build() *CatalogueSearchRequest {
	m0 := &CatalogueSearchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Next = b.Next
	x.xxx_hidden_Size = b.Size
	return m0
}

type CatalogueSearchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*CatalogueItem      `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next  string                 `protobuf:"bytes,2,opt,name=next"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CatalogueSearchResponse) Reset() {
	*x = CatalogueSearchResponse{}
	mi := &file_app_catalogue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogueSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogueSearchResponse) ProtoMessage() {}

func (x *CatalogueSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_catalogue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatalogueSearchResponse) GetItems() []*CatalogueItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *CatalogueSearchResponse) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *CatalogueSearchResponse) SetItems(v []*CatalogueItem) {
	x.xxx_hidden_Items = &v
}

func (x *CatalogueSearchResponse) SetNext(v string) {
	x.xxx_hidden_Next = v
}

type CatalogueSearchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*CatalogueItem
	Next  string
}

func (b0 CatalogueSearchResponse_builder) Build() *CatalogueSearchResponse {
	m0 := &CatalogueSearchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Next = b.Next
	return m0
}

// CatalogueItem is the public shape of an asset: what it is called and what it
// is, and nothing about where it is or who has it.
type CatalogueItem struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id    []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name  string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc  string                 `protobuf:"bytes,6,opt,name=desc"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CatalogueItem) Reset() {
	*x = CatalogueItem{}
	mi := &file_app_catalogue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogueItem) ProtoMessage() {}

func (x *CatalogueItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_catalogue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatalogueItem) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *CatalogueItem) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *CatalogueItem) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *CatalogueItem) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *CatalogueItem) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *CatalogueItem) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *CatalogueItem) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *CatalogueItem) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

type CatalogueItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The identifier, which says what kind of thing it is by carrying its domain
	// -- and says nothing about which tenant holds it.
	Id    []byte
	Alias string
	Name  string
	Desc  string
}

func (b0 CatalogueItem_builder) Build() *CatalogueItem {
	m0 := &CatalogueItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	return m0
}

var File_app_catalogue_proto protoreflect.FileDescriptor

const file_app_catalogue_proto_rawDesc = "" +
	"\n" +
	"\x13app/catalogue.proto\x12\x03app\"@\n" +
	"\x16CatalogueSearchRequest\x12\x12\n" +
	"\x04next\x18\x01 \x01(\tR\x04next\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"W\n" +
	"\x17CatalogueSearchResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.app.CatalogueItemR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"]\n" +
	"\rCatalogueItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc2W\n" +
	"\x10CatalogueService\x12C\n" +
	"\x06Search\x12\x1b.app.CatalogueSearchRequest\x1a\x1c.app.CatalogueSearchResponseB&Z\x1fgithub.com/lesomnus/custody/api\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_catalogue_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_catalogue_proto_goTypes = []any{
	(*CatalogueSearchRequest)(nil),  // 0: app.CatalogueSearchRequest
	(*CatalogueSearchResponse)(nil), // 1: app.CatalogueSearchResponse
	(*CatalogueItem)(nil),           // 2: app.CatalogueItem
}
var file_app_catalogue_proto_depIdxs = []int32{
	2, // 0: app.CatalogueSearchResponse.items:type_name -> app.CatalogueItem
	0, // 1: app.CatalogueService.Search:input_type -> app.CatalogueSearchRequest
	1, // 2: app.CatalogueService.Search:output_type -> app.CatalogueSearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_catalogue_proto_init() }
func file_app_catalogue_proto_init() {
	if File_app_catalogue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_catalogue_proto_rawDesc), len(file_app_catalogue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_catalogue_proto_goTypes,
		DependencyIndexes: file_app_catalogue_proto_depIdxs,
		MessageInfos:      file_app_catalogue_proto_msgTypes,
	}.Build()
	File_app_catalogue_proto = out.File
	file_app_catalogue_proto_goTypes = nil
	file_app_catalogue_proto_depIdxs = nil
}
